#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"
. "${script_path}/lib/traps"
. "${script_path}/lib/utils"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

# Pull image.
id=$(podman ps -a -f 'name=mysql' | grep -Fv 'CONTAINER' || true | head -n 1 | cut -d ' ' -f 1)
if test -z "${id}"; then
  sudo mkdir -p /run/mysqld
  sudo chown -R root:root /run/mysqld
  sudo chmod -R 777 /run/mysqld
  mkdir -p /var/lib/mysql
  mkdir -p /run/mysqld
  if test ! -e /var/lib/mysql/mysql.sock && test ! -L /var/lib/mysql/mysql.sock; then
    ln -s /run/mysqld/mysqld.sock /var/lib/mysql/mysql.sock
  fi
  MYSQL_ROOT_PASSWORD=keatest podman run -d -e 'MYSQL_ROOT_PASSWORD' \
    --name 'mysql' -p '3306:3306' -v '/run/mysqld:/run/mysqld' \
    --rm "${@}" 'mariadb'
fi

# Start container.
if test "$(podman inspect 'mysql' || true | jq -r '.[].State.Status')" != 'running'; then
  podman start 'mysql'
fi

# Wait to start.
"${script_path}/wait-for-mysql" $(additional-options)

# Adjust time zone.
timezone="$(timedatectl | grep 'Time zone' | cut -d ':' -f 2 | cut -d '(' -f 1 | xargs)"
mysql -h 127.0.0.1 -u root --password='keatest' -e "SET GLOBAL time_zone = '${timezone}'"
