#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

while true; do
  for user in postgres keatest; do
    export PGPASSWORD="${user}"
    if timeout 4s psql -h 127.0.0.1 -U "${user}" <<< '\q' 2> /dev/null; then
      break 2
    fi

    sleep 1
  done
done
