#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"

argument 'simple' 'empty_superuser_password' '-e|--empty' 'use no password for the superuser'

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

while true; do
  # Before first startup
  if "${empty_superuser_password-false}"; then
    unset PGPASSWORD
  else
    export PGPASSWORD=keatest
  fi
  if timeout 4s psql -U postgres <<< '\q'; then
    break
  fi
  unset PGPASSWORD

  # After first startup
  export PGPASSWORD=keatest
  if psql -U keatest <<< '\q'; then
    break
  fi
  unset PGPASSWORD

  sleep 1
done
