#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

name="$(basename "$(pwd)")"
dh_make -e andrei.pavel@mail.com -f "../${name}.tar.gz" -p "${name}_1.0" || true
dpkg-buildpackage -b -rfakeroot -uc -us
