#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"

argument 'simple' 'show_only' '-s|--show-only' 'only show command'

allow-extra-parameters

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

# Default arguments
test -z "${show_only+x}" && show_only=false

#------------------------------------------------------------------------------#

toplevel="$(git rev-parse --show-toplevel)"
prefix='/opt/dhcp'

if ${show_only}; then
  e='echo'
else
  e=
fi

if test ! -f ./configure; then
  ${e} autoreconf -f -i
fi

if test ! -f ./Makefile; then
  ${e} ./configure    \
    --prefix="${prefix}"                \
    --enable-binary-leases              \
    --enable-bind-install               \
    --enable-debug                      \
    --enable-dependency-tracking        \
    --enable-dhcpv4o6                   \
    --enable-early-chroot               \
    --enable-ipv4-pktinfo               \
    --enable-libtool                    \
    --enable-log-pid                    \
    --enable-maintainer-mode            \
    --enable-paranoia                   \
    --enable-relay-port                 \
    --enable-use-sockets                \
    --with-atf                          \
    --with-bind-extra-config            \
    --with-ldap                         \
    --with-ldap-gssapi                  \
    --with-ldapcrypto                   \
    "${@}"
fi

# Build twice to succeed. :)
${e} make -j "$(procs)" || \
${e} make -j "$(procs)"

${e} make -j "$(procs)" -C keama
