#!/bin/bash

# Copyright (C) 2019-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

directories=$(find . -type f -name 'Makefile.am' | xargs dirname | sort -V | uniq)
directory_count=$(printf '%s\n' "${directories}" | wc -l)
while true; do
  compiled_directory_count=0
  for directory in ${directories}; do
    compiled_directory_count=$(( compiled_directory_count + "$(find "${directory}" -mindepth 1 -maxdepth 1 -type d -name '.libs' | wc -l)" ))
  done
  loading-bar -n ${compiled_directory_count} ${directory_count}
  sleep 1
done
