#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

i=0
while true; do
  ssid="$(cat ${HOME}/.config/.wifi-list.yml | yaml2json - | jq ".[\"wifi_access_points\"][${i}]".ssid)"
  passkey="$(cat ${HOME}/.config/.wifi-list.yml | yaml2json - | jq ".[\"wifi_access_points\"][${i}]".passkey)"
  if [[ "${ssid}" == "null" || "${passkey}" == "null" ]]; then
    break
  fi
  /usr/lib/plainbox-provider-checkbox/bin/create_connection wifi --security wpa --key "${passkey}" "${ssid}"
  (( i++ ))
done
