#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
PATH="${PATH}:${SCRIPT_PATH}"

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

find . -iname "${1-.}" -print | while read -r i; do
  cpplint "${i}"
done
