#!/bin/bash

# Copyright (C) 2019-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

#------------------------------------------------------------------------------#

executable=${1}
shift

if ! test -f "${executable}-debug"; then
  cp "${executable}" "${executable}-debug"
  sed -i.tmp 's#exec "\$progdir/\$program"#exec cgdb --args "$progdir/$program"#g' "${executable}-debug"
fi

"${executable}-debug" "${@}"
