#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

# Ask user for confirmation.
whiptail --title "Removing the song" --yesno "Do you really want to delete the song \n$(mpc | head -n 1)?" 0 0

# If Yes, then 0 is returned, else 1.
if (( ${?} == 0 ));then
    song_to_remove="$(mpc | head -n 1)"
    playlist_position="$(mpc -f %position% | head -n 1)"
    # Delete the song.
    rm "$(mpc -f %file% | head -n 1 | sed 's/^/\/home\/andrei\/Dropbox\/Apps\/streamboxr\//')"
    if (( ${?} == 0 )); then
        # Remove the song from playlist.
        mpc del "${playlist_position}"
        # Write to log file.
        printf '%s\\n' "[$(get-date)] -> '$song_to_remove' is now deleted..." >> "${HOME}/.mpdremove.log"
    fi
fi
