#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

configure-kea

toplevel="$(git rev-parse --show-toplevel)"
pushd "${toplevel}" > /dev/null

sudo pkill -f change-Makefile-for-distcheck
change-Makefile-for-distcheck &

make -j "$(procs)" distcheck

popd > /dev/null
