#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

argument 'positional' 'criteria' 'criteria to search by'

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

mandatory criteria

#------------------------------------------------------------------------------#

if ! command -v turtle 2>&1 > /dev/null; then
  go get -u github.com/hackebrot/turtle/cmd/turtle
fi

turtle -i ' ' search "${criteria}" | grep '"char"' | cut -d ' ' -f 4 | cut -d '"' -f 2 | xargs
