#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

allow-extra-parameters

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

for i in $(find ~/work/isc -mindepth 1 -maxdepth 1 -type d \
  -name 'kea*' \
  -and -not -name 'kea.wiki' \
  -and -not -name 'kea-clean' \
  -and -not -name 'kea-hackathon' \
  -and -not -name 'kea-old' \
  -and -not -name 'kea-packaging' \
  -and -not -name 'kea-premium' \
  -and -not -name 'kea-premium*' \
  | sort -uV); do
  printf '=== %s ===\n' "${i}"
  pushd "${i}" > /dev/null
  "${@}"
  popd > /dev/null
done
