#!/bin/bash

# Copyright (C) 2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

cat kea-*-aggregated-*.xml | xq '.' | grep -B1 failure | grep -Eo 'testcase.*time' | sort -uV | cut -d '"' -f 2,4,8 | sed 's/"/ | /g' | sort -uV
