#!/bin/bash

# Copyright (C) 2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/traps"

argument 'positional' 'binary' ''
argument 'positional' 'core' ''

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

t() {
  trap="${trap-}
${*}"
  traps "${trap}"
}

t 'rm -f /tmp/gdb-commands.txt'
printf 'quit\n' > /tmp/gdb-commands.txt
for i in $(gdb "${binary}" "${core}" -x /tmp/gdb-commands.txt |& grep -F "warning: Can't open file" | cut -d  ' ' -f 5); do
  if test ! -e "${i}"; then
    file=$(basename "${i}")
    escaped_file=$(printf '%s' "${file}" | sed 's/\+/\\\+/g;s/\./\\\./g')
    your_file=$(locate "${file}" | grep -Ev 'docker|/home|\.libs' | grep -E "/${escaped_file}$" | head -n 1 || true)
    if test -n "${your_file}"; then
      mkdir -p "$(dirname "${i}")"
      ln -s "${your_file}" "${i}"
      t "rm -f ${i}"
      printf '=> %s -> %s\n' "${file}" "${your_file}"
    else
      printf '=> %s not found\n' "${file}"
    fi
  fi
done
gdb "${binary}" "${core}"
