#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

ip_address="$(ip addr show | grep 'inet ' | grep ' dynamic' | tr -s ' ' | cut -d ' ' -f 3)"
result=${?}
if (( result == 0 )) && [[ ! -z ${ip_address} ]]; then
  printf 'online: %s\n' "${ip_address}"
else
  printf 'offline\n'
fi
