#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

file='/usr/local/share/rfc.txt'

if [[ -f "${file}" ]]; then
  n="$(cat "${file}")"
else
  n=1
fi

rfc "${n}"

printf '%d' "$(( n + 1 ))" > "${file}"
