#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

song='♪'

song+=" $(mpc | head -n 2 | tail -n 1 | cut -d ' ' -f1)"
song+=" $(mpc 2>&1 | head -n 1)"
song="${song:0:64}"

printf '%s\n' "${song}"
