#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

if command -v acpi 2>&1 > /dev/null; then
  info="$(acpi -b | sed -e 's@.*\\([0-9]:\\) [^,]*,@\\1@' -e 's@remaining@@' | sed -e :a -e '$!N;s@\\n@| @;ta')"
  state="$(echo "${info}" | cut -d ':' -f2 | cut -d ',' -f 1 | xargs)"
  percentage="$(echo "${info}" | cut -d ',' -f2 | xargs)"
  numerical_percentage="${percentage%?}"
else
  battery_device="$(upower -e | grep 'BAT')"
  info="$(upower -i "${battery_device}")"
  state="$(echo "${info}" | grep 'state' | tr -d ' ' | cut -d ':' -f2)"
  percentage="$(echo "${info}" | grep 'percentage' | tr -d ' ' | cut -d ':' -f2)"
  numerical_percentage="${percentage%?}"
fi

case "${state}" in
  'full'|'Full'|'fully-charged'|'Fully-charged') battery_icon='☻' ;;
  'charging'|'Charging') battery_icon='⚡' ;;
  'discharging'|'Discharging') battery_icon='☇' ;;
esac

printf '%s\n' "${battery_icon} ${percentage}"
