#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

#------------------------------------------------------------------------------#

declare -a arguments=()
for i in ${@}; do
  arguments+=( $(pss ${i} | grep -Eo '^[]*[0-9]+' | xargs) )
done

if (( ${#arguments[@]} == 0 )); then
  htop -t
else
  args="${arguments[@]}"
  htop -t -p ${args// /,}
fi
