#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

mkdir -p ~/.thunderbird
find ~/.thunderbird -type d -name '*.default' | xargs -I{} bash -c '
  cp ~/.config/templates/thunderbird/prefs.js {}/prefs.js;
  cp ~/.config/templates/thunderbird/session.json {}/session.json;
'
