#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

mkdir -p ~/.config/templates/libvirt
for i in ~/.config/templates/libvirt/*.xml; do
  domain=$(basename "${i}" | cut -d '.' -f 1)
  if virsh list --all | tail -n +3 | tr -s ' ' | cut -d ' ' -f 3 | grep "${domain}" > /dev/null; then
    printf 'Skipping %s, it is already defined...\n' "${domain}"
  else
    virsh define "${i}"
  fi
done
