#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

for i in $(tr -s ' ' < ~/.config/templates/cargo.pkg | grep -E '^[a-zA-Z]' | cut -d ' ' -f 1); do
  cargo install "${i}"
done

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)
