#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

dnf install $(grep -Fv 'copr:copr' < ~/.config/templates/dnf.pkg | cut -d ' ' -f 1 | xargs)
dnf copr install $(grep -F 'copr:copr' < ~/.config/templates/dnf.pkg | cut -d ' ' -f 1 | xargs)
