#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

mkdir -p ~/.config/templates/kde
for i in \
  'kwinrc' \
  'khotkeysrc' \
  'plasma-org.kde.plasma.desktop-appletsrc' \
; do
  cp ~/.config/templates/kde/${i} ~/.config/${i}
done
