#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

# apt-get install -y $(tr -s ' ' < ~/.config/templates/apt.pkg | cut -d ' ' -f 2)

for i in $(tr -s ' ' < ~/.config/templates/apt.pkg | cut -d ' ' -f 2); do
  apt-get install -y "${i}" || true
done
