#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

allow-extra-parameters

argument 'simple' 'sleep' '-s|--sleep' 'sleep between diffs'

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

file1=/tmp/monitor-changes-1
file2=/tmp/monitor-changes-2
rm -f "${file1}" "${file2}"
touch "${file1}" "${file2}"
while true; do
  eval "${@}" > "${file2}"
  diff_result=$(diff "${file1}" "${file2}") || true
  if test -n "${diff_result}"; then
    printf '%s\n' "${diff_result}"
    cp -f "${file2}" "${file1}"
  fi
  if ${sleep-false}; then
    sleep 1
  fi
done
