#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

nohup socat UNIX-LISTEN:/var/lib/mysql/mysql.sock,reuseaddr,fork TCP:127.0.0.1:3306 &> /dev/null &
