#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

if test -f /proc/cpuinfo; then
  grep -Fc proc < /proc/cpuinfo
else
  # FreeBSD
  dmesg | grep -E 'SMP' | grep -Eo '[0-9]+ CPUs' | cut -d ' ' -f 1 | head -n 1
fi
