#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

mandatory-command svg-term

#------------------------------------------------------------------------------#

rm -f /tmp/a.cast
LC_ALL=en_US.UTF-8 asciinema rec /tmp/a.cast
node --max-old-space-size=8192 $(which svg-term) --in /tmp/a.cast --out /tmp/a.svg
printf '%s\n' '/tmp/a.svg'
