#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

allow-extra-parameters

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

find ${1-.} -type f -exec grep -Iq . {} \; -exec sed -i.tmp -e :a -e 's/ *$//g' {} \;
