#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

argument 'positional' 'file' 'file to remove comments from'

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

mandatory file

#------------------------------------------------------------------------------#

tmp="/tmp/remove-comments-${file//\//-}.tmp"
grep -Ev '^\s*//|^\s*#|^\s*/\*.*\*/' "${file}" | sed '/\/\*/,/\*\//d;s#[^ ]+//.*$##g;s/#.*$//g' > "${tmp}"
mv "${tmp}" "${file}"
