#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

#------------------------------------------------------------------------------#

rsync --verbose --progress --human-readable --compress --archive --hard-links --one-file-system --acls --xattrs --update "${@}"
