#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

#------------------------------------------------------------------------------#

/usr/share/clang/run-clang-tidy.py -header-filter='.*' -checks='-clang-analyzer-optin.cplus
plus.VirtualCall,-modernize-use-override' -fix "${@}"
