#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

mkdir -p ~/.config/templates/libvirt
for i in $(virsh list --all | tail -n +3 | tr -s ' ' | cut -d ' ' -f 3); do
  virsh dumpxml "${i}" > ~/.config/templates/libvirt/"${i}.xml"
done
