#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

argument 'positional' 'input' 'input to process'

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

if test -n "${input+x}"; then
  aspell list < "${input}" 2> /dev/null
else
  for i in $(find . -type f \
        -name '*.ac' \
    -or -name '*.am' \
    -or -name '*.cc' \
    -or -name '*.h' \
    -or -name '*.in' \
    -or -name '*.js' \
    -or -name '*.mes' \
    -or -name '*.rst' \
    -or -name '*.sh' \
    -or -name '*.txt' \
    -or -name '*.uml' \
    -or -name '*.xml' \
  ); do
    aspell list < ${i} 2> /dev/null
  done
fi | sort -uV > /tmp/spellcheck-kea.txt

diff /tmp/spellcheck-kea.txt /etc/.spellcheck-kea.txt | grep -E '^<'
