#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

path="${HOME}/work/github.com/spike-desktop-electron"
if test ! -d "${path}"; then
  pushd "$(dirname "$(readlink -f "${path}")")" > /dev/null
  git clone 'https://github.com/ildella/spike-desktop-electron.git'
  popd
fi

pushd "${path}" > /dev/null
git checkout -- .
git pull
npm update
npm install
npm start
