#!/bin/bash

# Copyright (C) 2019-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

export GDK_CORE_DEVICE_EVENTS=1
export lang=en_GB.UTF-8

command -v subl3 && LANG="${lang}" LC_ALL="${lang}" LC_CTYPE="${lang}" subl3 "${@}"
command -v subl && LANG="${lang}" LC_ALL="${lang}" LC_CTYPE="${lang}" subl "${@}"
