#!/bin/bash

# Copyright (C) 2019-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"

(( EUID != 0 )) && exec sudo -- "${0}" "${@}" $(additional-options)

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

# Install newer compiler.
apt-get update
apt-get install -y                           \
  llvm-7-dev gcc-7 g++-7 libstdc++-7-dev     \
  llvm-8-dev gcc-8 g++-8 libstdc++-8-dev     \
  llvm-9-dev gcc-9 g++-9 libstdc++-9-dev
# apt-get purge -y \
#   llvm-10-dev gcc-10 g++-10 libstdc++-10-dev

# Set higher priority for newer compilers.
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 7
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-8 8
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 9
update-alternatives --remove clang /usr/bin/clang-10
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-7 7
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-8 8
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-9 9
update-alternatives --remove clang++ /usr/bin/clang++-10
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 7
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
update-alternatives --remove gcc /usr/bin/gcc-10
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 7
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
update-alternatives --remove g++ /usr/bin/g++-10

# Change the compiler to clang++.
update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 100
update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 100
update-alternatives --install /usr/bin/cc cc /usr/bin/clang 200
update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 200
