#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/spinner"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

start-spinner 'Recording...'
arecord -d 4 -f U8 /tmp/audio.wav
stop-spinner ${?}

start-spinner 'Playing...'
aplay /tmp/audio.wav
stop-spinner ${?}
