#!/bin/bash

# Copyright (C) 2017-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"

parse-parameters "${@}"
set -- "${EXTRA_PARAMETERS[@]}"

#------------------------------------------------------------------------------#

vim +PlugUpgrade +qall
vim +PlugClean +qall
vim +PlugUpdate +qall

# Also run as root.
if (( EUID != 0 )); then
  exec sudo su -m root -c "${0} ${@} $(additional-options)"
fi
