#!/bin/bash

# Copyright (C) 2020-2021 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Header
script_path="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "${script_path}/lib/header"
. "${script_path}/lib/spinner"
. "${script_path}/lib/utils"

argument 'positional' 'line' 'line to wait for'
argument 'positional' 'file' 'file to wait in'
argument 'positional' 'timeout' 'how much time to wait before giving up, default: 30s'

#------------------------------------------------------------------------------#

function read-offset() {
  local file
  file="$(readlink -f "${1}")"
  file="${file//-/_}"
  file="${file//./_}"
  file="${file//\//_}"
  offset="OFFSET_${file}"
  printf '%s' "${!offset-1}"
}

function update-offset() {
  local file
  file="$(readlink -f "${1}")"
  file="${file//-/_}"
  file="${file//./_}"
  file="${file//\//_}"
  read -r "OFFSET_${file}" <<< "${2}"
}

function update-line-count-for-file() {
  mandatory-command readlink
  mandatory-command wc
  file="$(readlink -f "${1}")"
  line_count_in_file="$(wc -l "${file}" | cut -d ' ' -f 1)"
  update-offset "${file}" "$(( line_count_in_file + 1 ))"
}

mandatory-command readlink
mandatory-command sed
mandatory-command wc
line="$(printf '%q' "${1}")"
line="${line//\//\\\/}"
file="$(readlink -f "${2}")"
timeout="${3-30 seconds}"
finish="$(date +%s -d "${timeout}")"

# Wait for file to be created.
while [[ ! -f ${file} ]]; do
  sleep 1
done

while true; do
  # Check if timeout has passed.
  if (( "${finish}" < "$(date +%s)" )); then
    printf "
ERROR: Timed out after ${timeout} of waiting for line in file:
+- line: ${line}
+- file: ${file}

%s\n" "$(tail "${file}")" >&2
    exit 1
  fi

  offset="$(read-offset "${file}")"
  # Check if we have reached end of file.
  line_count_in_file="$(wc -l "${file}" | cut -d ' ' -f 1)"
  if (( offset > line_count_in_file )); then
    sleep 1
    continue
  fi

  line_number_found="$(sed "${offset},${line_count_in_file}!d;/${line}/!d;=" "${file}" | head -n 1)" || true

  if [[ -z "${line_number_found}" ]]; then
    # not found
    update-offset "${file}" "$(( line_count_in_file + 1 ))"
  else
    # found
    update-offset "${file}" "$(( line_number_found + 1 ))"
    break
  fi
done
